# Generated by Django 4.0 on 2021-12-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Space',
        ),
    ]
